//Doctor Appointment
export const GET_SPECIALITY = "GET_SPECIALITY";
export const GET_PATIENT_DOCTOR_SEARCH = "GET_PATIENT_DOCTOR_SEARCH";
export const GET_PARTICULAR_DOCTOR_SEARCH = "GET_PARTICULAR_DOCTOR_SEARCH";
export const GET_PARTICULAR_DOCTOR_SEARCH_CLINICSLOTS = "GET_PARTICULAR_DOCTOR_SEARCH_CLINICSLOTS";
export const POST_PATIENT_DOCTOR_BOOKING = "POST_PATIENT_DOCTOR_BOOKING";
export const GET_PATIENT_BOOKED_APPOINTMENTLIST = "GET_PATIENT_BOOKED_APPOINTMENTLIST";
export const GET_PATIENT_BOOKED_APPOINTMENTLIST_HISTORY = "GET_PATIENT_BOOKED_APPOINTMENTLIST_HISTORY";
export const GET_RESCHEDULED_DOCTOR_APPOINTMENT = "GET_RESCHEDULED_DOCTOR_APPOINTMENT";
export const GET_RESCHEDULED_DOCTOR_APPOINTMENT_CLINICSLOTS = "GET_RESCHEDULED_DOCTOR_APPOINTMENT_CLINICSLOTS";
export const PUT_FAVOURITE_ADD_REMOVE = "PUT_FAVOURITE_ADD_REMOVE";
export const GET_MY_APPOINTMENT_PRESCRIPTION_HISTORY = "GET_MY_APPOINTMENT_PRESCRIPTION_HISTORY";

//Trainer
export const GET_TRAINERLIST_PATIENT = "GET_TRAINERLIST_PATIENT";
export const GET_PARTICULAR_TRAINER_DETAILS = "GET_PARTICULAR_TRAINER_DETAILS";

//dropdown
export const GET_DOCTOR_SERVICE_DROPDOWN = "GET_DOCTOR_SERVICE_DROPDOWN";

// Patient profile
export const GET_MEMBER_PROFILE="GET_MEMBER_PROFILE"
export const GET_PATIENT_HEALTHTIPS="GET_PATIENT_HEALTHTIPS"
export const GET_PATIENT_PERSCRIPTION="GET_PATIENT_PERSCRIPTION"
export const ADD_PATIENT_DETAILS="ADD_PATIENT_DETAILS"
export const UPDATE_PATIENT_DETAILS="UPDATE_PATIENT_DETAILS"
export const DELETE_MEMBER="DELETE_MEMBER"
export const GET_RELATIONSHIP="GET_RELATIONSHIP"
export const PARTICULAR_VACCINATION="PARTICULAR_VACCINATION"
export const GET_PERSCRIPTION="GET_PERSCRIPTION"
export const UPDATE_BASIC_DETAILS="UPDATE_BASIC_DETAILS"