//Doctor Appointment
export const GET_SPECIALITY = "GET_SPECIALITY";
export const GET_PATIENT_DOCTOR_SEARCH = "GET_PATIENT_DOCTOR_SEARCH";
export const GET_PARTICULAR_DOCTOR_SEARCH = "GET_PARTICULAR_DOCTOR_SEARCH";
export const GET_PARTICULAR_DOCTOR_SEARCH_CLINICSLOTS = "GET_PARTICULAR_DOCTOR_SEARCH_CLINICSLOTS";
export const POST_PATIENT_DOCTOR_BOOKING = "POST_PATIENT_DOCTOR_BOOKING";
export const GET_PATIENT_BOOKED_APPOINTMENTLIST = "GET_PATIENT_BOOKED_APPOINTMENTLIST";
export const GET_PATIENT_BOOKED_APPOINTMENTLIST_HISTORY = "GET_PATIENT_BOOKED_APPOINTMENTLIST_HISTORY";
export const GET_RESCHEDULED_DOCTOR_APPOINTMENT = "GET_RESCHEDULED_DOCTOR_APPOINTMENT";
export const GET_RESCHEDULED_DOCTOR_APPOINTMENT_CLINICSLOTS = "GET_RESCHEDULED_DOCTOR_APPOINTMENT_CLINICSLOTS";
export const PUT_FAVOURITE_ADD_REMOVE = "PUT_FAVOURITE_ADD_REMOVE";
export const GET_MY_APPOINTMENT_PRESCRIPTION_HISTORY = "GET_MY_APPOINTMENT_PRESCRIPTION_HISTORY";

//Trainer
export const GET_TRAINERLIST_PATIENT = "GET_TRAINERLIST_PATIENT";
export const GET_PARTICULAR_TRAINER_DETAILS = "GET_PARTICULAR_TRAINER_DETAILS";

//dropdown
export const GET_DOCTOR_SERVICE_DROPDOWN = "GET_DOCTOR_SERVICE_DROPDOWN";

//Report
export const LAB_RESULT_MEMBERLIST="LAB_RESULT_MEMBERLIST";
export const PARTICULAR_MEMBER_LABRESULT="PARTICULAR_MEMBER_LABRESULT";

//Lab History
export const GET_LAB_LIST="GET_LAB_LIST";
export const GET_PARTICULAR_LAB_DETAILS="GET_PARTICULAR_LAB_DETAILS";

//Clinical Lab
export const GET_LAB_PACKAGE="GET_LAB_PACKAGE";
export const GET_LAB_TEST="GET_LAB_TEST"

//PatientProfile
export const GET_PATIENT_PROFILE="GET_PATIENT_PROFILE";